### ISSUE TITLE
error occurs when accessing the datacache from localhost

### ISSUE THREAD

**Issue by yingqiaogit** [glynnbird/bluemix_datacache#1]
I am trying to run my app on localhost first before moving it to bluemix. I added a setcredentials function to the library, and set the credentials from app.js. The credentials are copied from the bluemix VCAP_SERVICES

Run a put in app.js as:
  datacache.put("test",{"first":1}, function(err,body){
        if (err)
        {
            console.log("cache error " + JSON.stringify(err));
        }
        else{
            console.log("cache result: " + JSON.stringify(body));
        }
    });

error message is as: 
cache error{"message":"connect ETIMEDOUT","stack":"Error: connect ETIMEDOUT\n    at exports._errnoException (util.js:746:11)\n    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)","code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"}

Any suggestion?

**Comment by yingqiaogit** [comment]
https://developer.ibm.com/answers/questions/166439/how-can-i-access-data-cache-from-localhost.html
